model: vit_small_patch16_224.dino
checkpoint: output/train/vit_small_dinov1_gastronet5M/final_eval
multi_seed: true
results_dir: output/val/vit_small_dinov1_gastronet5M
split: test
num_classes: 2
include_index: true
topk: 2
fullname: true
no_console_results: true