batch_size: 64
bce_loss: true
epochs: 100
eval_metric: auc_pr
log_interval: 20
lr: 0.0001
model: vit_large_patch16_dinov3_qkvb.lvd1689m
num_classes: 2
output: 'output/train/vit_large_dinov3_lvd1689m'
experiment: 'final_eval'
pretrained: true
repeat_class: 1
repeat_factor: 5  
sched: cosine
scale:
- 0.85
- 1.0
train_split: train
val_split: val
warmup_epochs: 5
workers: 4
train_interpolation: bicubic
train_crop_mode: rkrr
crop_pct: 1.0
crop_mode: border
vflip: 0.5
rotation: true
opt: adamw
opt_betas: [0.9, 0.999]
seed:
- 0
- 42
- 84
- 126
- 168